apiVersion: v1
kind: Pod
metadata:
  name: mytest-allure
spec:
  containers:
    - name: mytest-allure
      image: bash
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 120;done"]
      volumeMounts:
        - name: allure
          mountPath: /tmp/allure-results
  restartPolicy: Never
  volumes:
    - name: allure
      persistentVolumeClaim:
        claimName: allure