apiVersion: v1
kind: Pod
metadata:
  name: mytest-allure
spec:
  containers:
    - name: mytest-allure
      image: bash
      command: ["rm"]
      args: ["-r", "/tmp/allure-results"]
      volumeMounts:
        - name: allure
          mountPath: /tmp/allure-results
  restartPolicy: Never
  volumes:
    - name: allure
      persistentVolumeClaim:
        claimName: allure